# Generated by Django 2.2.5 on 2019-09-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mirror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='mirror/')),
                ('price', models.IntegerField(default=0)),
                ('short_description', models.CharField(default=0, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Photofon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='fotofon/')),
                ('price', models.IntegerField(default=0)),
                ('short_description', models.CharField(default=0, max_length=300)),
            ],
        ),
    ]
