# Generated by Django 2.2.5 on 2019-09-10 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mirror',
            options={'verbose_name': 'Зеркало', 'verbose_name_plural': 'Зеркала'},
        ),
        migrations.AlterModelOptions(
            name='photofon',
            options={'verbose_name': 'Фотофон', 'verbose_name_plural': 'Фотофоны'},
        ),
    ]
